### ISSUE TITLE
深色模式下网页显示异常

### ISSUE THREAD

**Issue by fenglielie** [iw17/vscode#1]
如图
<img width="834" alt="EA2C7079BB2E1667A3F2E65E4D88E834" src="https://user-images.githubusercontent.com/51266402/222885189-f4a54973-3fc5-487f-9341-c71f1282d0de.png">

**Comment by iw17** [comment]
谢谢反馈，我刚才试了一下，在我这边是深色模式和浅色完全一样，最晚明天修好

**Comment by iw17** [comment]
已解决，解决办法：设置文字颜色为背景颜色的补色，同时为了效果清晰，适当修改了链接文本的颜色

另外经过测试，华为鸿蒙3.0.0.202系统自带浏览器可能有bug，无论手机如何设置，prefers-color-scheme总是light；QQ和微信的浏览器也是这样；而Android 64位版手机百度APP 13.9.0.10版本的prefers-color-scheme则总是no-preference，但百度浏览器的这个现象暂时不排除是我手机设置原因

**Comment by iw17** [comment]
又发现新问题了，就是在手机深色模式下，微信自带浏览器实际上可以将prefers-color-scheme置为dark，但在背景颜色设置为transparent时显示白色；而QQ自带浏览器则总是light。我正在针对这个现象重新修改

**Comment by iw17** [comment]
用Nextra重构以后可以自动适配系统浅色/深色模式，若适配不正确还可以在网页下方手动更改，经测试，华为鸿蒙3系统手机自带浏览器已正常，百度APP Android 64位版依然存在问题，目前初步怀疑是百度APP或Nextra的bug
