### ISSUE TITLE
用vscode写LaTeX

### ISSUE THREAD

**Issue by StuCjk** [iw17/vscode#3]
网站中配置vscode写LaTeX的教程已经过时，可不可以参考或者链接到https://ctan.org/pkg/install-latex-guide-zh-cn 以获取最新配置方法qwq

**Comment by iw17** [comment]
谢谢反馈，是三个链接都过时了已经不正确了嘛？我点开看这个链接，好像是安装LaTeX的教程而不是给VS Code配置LaTeX环境的教程？

**Comment by StuCjk** [comment]
> 谢谢反馈，是三个链接都过时了已经不正确了嘛？我点开看这个链接，好像是安装LaTeX的教程而不是给VS Code配置LaTeX环境的教程？

都过时了qwq。这个文档包含了安装与不同编辑器的配置方式，是LaTeX入门必读文档，其中介绍的vscode配置适合新手参考

**Comment by iw17** [comment]
欧了，白天起来再整

**Comment by iw17** [comment]
能不能麻烦发一下这个文档里直接指向介绍VS Code配置的链接？我在这个链接里只看到了pdf的第5.5节简短提到了VS Code，是我没找着还是本来就只有这块提到了？如果这份文档里真的只有这一块提到VS Code，那这份文档在“给VS Code配置LaTeX环境”这个问题上的指导性可能还不如那三篇知乎？

我白天会在文档里添加这个链接给LaTeXers参考，但这里毕竟是VS Code群，不是LaTeX群，所以如果这篇文档里的VS Code部分很简略，并且原文三篇教程依然适用，那就不会替换原文链接

另外如果有时间可以举出三篇教程具体哪块过时或者不好使的一个或几个例子嘛？非常感谢

**Comment by iw17** [comment]
这个链接已经加入并提交到本地`dev`分支，下次网站更新时push上来
